Support Bio NER using stanza processor
asyml/forte-wrappers pull request #111
Opened 2022-06-14 04:29 UTC by Leolty

This PR fixes asyml/ForteHealth/issues/19.

### Description of changes
I add NER configuration in stanza processor
with the following configuration:
`
config = {
  "processors":{
       "tokenize":"default",
       "pos":"defualt",
       "lemma":"default",
       "depparse":"default",
       "ner":"i2b2"
        },
  "lang": "en",
  "use_gpu": False,
}
`
You can get biological/ medical/ clinical EntityMention of your input data. (This is BioNER)

Also, you can feel free to change the model in the configuration, 
for example, with the following  configuration:
`
config = {
  "processors":{
       "tokenize":"default",
       "pos":"defualt",
       "lemma":"default",
       "depparse":"default",
       "ner":"ontonotes"
        },
  "lang": "en",
  "use_gpu": False,
}
`
You can get basic EntityMention of your input data. (This is NER) 

### Possible influences of this PR.
Support basic NER and Bio NER using stanza processor: all you need to do is modify the configuration according to your requirements.

### Test Conducted
All the test data are explicitly described in stanfordnlp_processor_test.py, and the test is successful.

2022-06-14 06:45 UTC, Leolty commented
I suddenly found a problem with the naming of processors: it should be `StanfordNLPProcessor` instead of `Standfor**d**NLPProcessr`. I will add this issue after this PR is merged.

2022-06-15 05:01 UTC, Piyush13y requested changes

2022-06-15 05:01 UTC, Piyush13y commented on src/stanza/fortex/stanza/stanza_processor.py
> +            processors=self.configs.processors.todict(),
Again, we can just use `self.processors` here right? Since it is being set when `self.set_up()` is called in L58.

2022-06-15 10:44 UTC, Leolty commented
@Piyush13y  I have resolved all the changes you requested and change the styles of the test codes by using ddt. 

Is it inevatible to use hardcoding to check pos, lemma, dependency parsing, ner and bio ner?

I noticed that the tests in nltk and icd coding both use this kind of hardcodings.

2022-06-16 05:39 UTC, Piyush13y commented
> @Piyush13y I have resolved all the changes you requested and change the styles of the test codes by using ddt.
> 
> Is it inevatible to use hardcoding to check pos, lemma, dependency parsing, ner and bio ner?
> 
> I noticed that the tests in nltk and icd coding both use this kind of hardcodings.

Unit tests do have the hardcoded component most times, since its generally the processing of a component that we are testing. Hence, we use pre determined results and compare the results with it to know its working in the intended manner. My comment was more about the way you were hardcoding, it wasnt needed to make a list of each token written explicitly when you could leverage `split() `method itself for this.

2022-06-17 15:59 UTC, Leolty commented
Bad news is that build errors come one after another. 

Does the workflows run automatically or it will run after an approval from a maintainer? It seems like I always waited more than one day for the results of the workflows.

2022-06-18 10:34 UTC, Leolty commented
@Piyush13y Could you plz review the requested changes. I have resolved all. XD

2022-06-18 19:07 UTC, Piyush13y approved these changes

2022-06-18 19:07 UTC, merged